'use client';

import React, { useState } from 'react';
import { ShieldAlert, Fingerprint, ArrowRight, RefreshCw, KeyRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useRouter } from 'next/navigation';
import toast from 'react-hot-toast';

export default function MfaVerifyPage() {
  const router = useRouter();
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length < 6) return;
    
    setLoading(true);
    try {
      const res = await fetch('/api/auth/mfa/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code })
      });
      
      const data = await res.json();
      if (data.success) {
        toast.success('Identity verified');
        router.push('/dashboard');
      } else {
        toast.error(data.error || 'Verification failed');
      }
    } catch (err) {
      toast.error('Connection failure during verification');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4">
      <div className="max-w-md w-full relative">
        {/* Glow effect */}
        <div className="absolute inset-0 bg-indigo-600/10 blur-[120px] rounded-full" />
        
        <div className="relative bg-slate-900 border border-slate-800 rounded-[2.5rem] p-10 shadow-2xl flex flex-col items-center">
          <div className="w-20 h-20 bg-indigo-600/10 rounded-3xl flex items-center justify-center mb-8 border border-indigo-500/20 shadow-inner">
            <Fingerprint className="w-10 h-10 text-indigo-500" />
          </div>

          <div className="text-center mb-10">
            <h1 className="text-3xl font-black text-white tracking-tight">Identity Check</h1>
            <p className="text-slate-500 mt-2 font-medium">Please enter the security token generated by your authenticator device.</p>
          </div>

          <form onSubmit={handleVerify} className="w-full space-y-8">
            <div className="space-y-4">
              <div className="relative">
                <KeyRound className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-500" />
                <input
                  required
                  type="text"
                  placeholder="000 000"
                  maxLength={6}
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/[^0-9]/g, ''))}
                  className="w-full bg-slate-800 border-2 border-slate-700 rounded-2xl py-5 pl-12 pr-4 text-center text-4xl font-black text-indigo-400 tracking-[0.5em] focus:outline-none focus:border-indigo-500 transition-all font-mono"
                />
              </div>
              <p className="text-[10px] text-slate-600 font-bold uppercase tracking-widest text-center">Enter your 6-digit backup or TOTP code</p>
            </div>

            <Button
              disabled={loading || code.length < 6}
              className="w-full h-16 bg-indigo-600 hover:bg-indigo-700 text-white font-black rounded-2xl text-lg shadow-xl shadow-indigo-600/20 flex items-center justify-center gap-3 group disabled:opacity-50 transition-all"
            >
              {loading ? <RefreshCw className="w-6 h-6 animate-spin" /> : (
                <>
                  Verify Access
                  <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </>
              )}
            </Button>
          </form>

          <div className="mt-12 p-5 bg-rose-500/5 border border-rose-500/10 rounded-2xl flex items-start gap-4">
            <ShieldAlert className="w-5 h-5 text-rose-500 shrink-0 mt-0.5" />
            <p className="text-xs text-slate-500 leading-relaxed font-medium">
              If you have lost access to your device, please use one of your <span className="text-slate-400 font-bold">Emergency Backup Codes</span> to regain entry.
            </p>
          </div>
        </div>

        <div className="mt-8 text-center">
           <button className="text-slate-600 hover:text-indigo-400 transition-colors text-xs font-black uppercase tracking-widest">
             Switch Accounts
           </button>
        </div>
      </div>
    </div>
  );
}
